### ISSUE TITLE
Jackson Reeves - Disappearing tiles

### ISSUE THREAD

**Issue by jtreeves** [jtreeves/matches-and-patches#10]
- [x] After a certain point, some tiles just display as "undefined" in the user's or opponent's main display window (the tiles that appear above and below the game board)
- [ ] I think it has to do with the checkUserPairs() function at app.js:392; perhaps they get reassigned to something in that function that clears their HTML content (but I'm unsure where or why)
- [ ] Note: The statuses for the tiles don't even appear marked as "user" or "opponent" in the consoled version of the tiles array (there should always be four tiles as "user" and four as "opponent," but at a certain point, that number dips to three or two)
![Screen Shot 2020-11-09 at 4 31 10 PM](https://user-images.githubusercontent.com/15839768/98598799-ff6b3c00-22a8-11eb-830e-51112154c582.png)

**Comment by jtreeves** [comment]
Fixed the issue by adjusting some things about userPatch and opponentPatch (see the other issue about what specifically; evidently, the two issues were interrelated). However, now all the opponent's tiles are disappearing one at a time. I assume it has something to do with opponentTile that isn't happening to userTile. Need to investigate.

**Comment by jtreeves** [comment]
Nevermind, it seems like that was a fluke. The disappearing issue persists for both the user and the opponent equally.

**Comment by jtreeves** [comment]
```javascript
if (userTile.color === userTopTile.color || userTile.number === userTopTile.number || userTile.shape === userTopTile.shape) {
        userPatch.status = 'user captured'
        userTopPatch.status = 'user captured'
        console.log('USER MATCHED WITH TOP')
    } else if (userTile.color === userBottomTile.color || userTile.number === userBottomTile.number || userTile.shape === userBottomTile.shape) {
        userPatch.status = 'user captured'
        userBottomPatch.status = 'user captured'
        console.log('USER MATCHED WITH BOTTOM')
    } else if (userTile.color === userLeftTile.color || userTile.number === userLeftTile.number || userTile.shape === userLeftTile.shape) {
        userPatch.status = 'user captured'
        userLeftPatch.status = 'user captured'
        console.log('USER MATCHED WITH LEFT')
    } else if (userTile.color === userRightTile.color || userTile.number === userRightTile.number || userTile.shape === userRightTile.shape) {
        userPatch.status = 'user captured'
        userRightPatch.status = 'user captured'
        console.log('USER MATCHED WITH RIGHT')
    } else {
        console.log('NO MATCH FOR USER')
    }
```

**Comment by romebell** [comment]
- [ ] Resource to use
```js
switch (new Date().getDay()) {
  case 0:
    day = "Sunday";
    break;
  case 1:
    day = "Monday";
    break;
  case 2:
     day = "Tuesday";
    break;
  case 3:
    day = "Wednesday";
    break;
  case 4:
    day = "Thursday";
    break;
  case 5:
    day = "Friday";
    break;
  case 6:
    day = "Saturday";
}
```

**Comment by romebell** [comment]
This may work. 🧪

```js
let mainCase = userTile.color === userTopTile.color || userTile.number === userTopTile.number || userTile.shape === userTopTile.shape;
let case1 = userTile.color === userBottomTile.color || userTile.number === userBottomTile.number || userTile.shape === userBottomTile.shape;
let case2 = userTile.color === userLeftTile.color || userTile.number === userLeftTile.number || userTile.shape === userLeftTile.shape;
let case3 = userTile.color === userRightTile.color || userTile.number === userRightTile.number || userTile.shape === userRightTile.shape;

switch(mainCase) {
    userPatch.status = 'user captured'
    userTopPatch.status = 'user captured'
    console.log('USER MATCHED WITH TOP')
    
    case case1:
        userPatch.status = 'user captured'
        userBottomPatch.status = 'user captured'
        console.log('USER MATCHED WITH BOTTOM')
    case case2:
        userPatch.status = 'user captured'
        userLeftPatch.status = 'user captured'
        console.log('USER MATCHED WITH LEFT')
    case case3:
        userPatch.status = 'user captured'
        userRightPatch.status = 'user captured'
        console.log('USER MATCHED WITH RIGHT')
    default:
        console.log('NO MATCH FOR USER')
}
```

**Comment by jtreeves** [comment]
I tried something similar (instead of defining case1 = all of that, I just plugged in the chain of conditional statements after 'case'; it was long, but JS handled it). It created a new issue (whenever it matched with one patch, it said it matched with two patches). It also didn't solve the disappearing tiles problem.

I definitely need something like a switch case, though, because I need to capture all the patches in play (e.g., capture the top, bottom, left, and right, if all of them match) instead of just one. I think I'm going to try chaining if statements (as in, I'll have one 'if' without an 'else,' and after I'll have another 'if' without an 'else,' etc.).

For the disappearing tiles issue, I'm going to try console logging the each player's tiles at the beginning of each move, so I can see what's showing up as 'undefined,' and then inspect it in a console log of the tiles array.

**Comment by jtreeves** [comment]
After console logging, I was able to narrow down on the problem area. Every instance when the tile didn't show up and "undefined" showed up in its place occurred when the chooseTile() function had to call itself within its own else block. The problem only happened after chooseTile() ran once and chose an index in the array that had an object that was already being used. When it ran the second time and found an inactive tile, it returned it, but as an empty shell. I thought callback functions were okay? Here's the code:

```javascript
function chooseTile() {
    let choice = ''
    let randomTileIndex = generateRandomTileIndex()
    if (tiles[randomTileIndex].status === 'inactive') {
        choice = tiles[randomTileIndex]
        console.log('inside chooseTile()')
    } else {
        chooseTile()
    }
    return choice
}
```

**Comment by jtreeves** [comment]
I think I solved it! Inside the else block, I changed this:
```javascript
chooseTile()
```
to this:
```javascript
choice = chooseTile()
```

So far, no more issues!

**Comment by jtreeves** [comment]
Yup! I just played through an entire game without any issue, and there was even an instance that I could see in the console log when the chooseTile() function had to call itself again after already choosing an active tile.
