### ISSUE TITLE
Jackson Reeves - Displaying board on landing page

### ISSUE THREAD

**Issue by jtreeves** [jtreeves/matches-and-patches#2]
- [x] Game boards will not display on the landing page (there are two, one labeled with the class 'board' and the other with the class 'small-board', and neither are showing up)
- [x] Ideally, I want the CSS for the boards to be in a separate CSS file called board.css; they aren't currently in there because I thought that might be causing the issue, but once this bug is resolved, can I move them there?

**Comment by romebell** [comment]
Great work so far! 

Issue solved ✅
