### ISSUE TITLE
Jackson Reeves - JS either not grabbing element or not letting me access it in function

### ISSUE THREAD

**Issue by jtreeves** [jtreeves/matches-and-patches#3]
- [x] When I run my page, I get "ReferenceError: Cannot access uninitialized variable." [The console says it runs into this error at line 23 of my app.js file.]
- [x] I believe there is a problem with how my JS grabs the element called tiles or how I'm setting up my function
![Screen Shot 2020-11-02 at 4 28 38 PM](https://user-images.githubusercontent.com/15839768/97921106-785a1900-1d28-11eb-8981-301afafae34f.png)

**Comment by jtreeves** [comment]
I just tried logging my tiles array, and nothing showed up in the console (there should 64 elements). However, the console is still telling me that I have the error on the line that begins with tiles[0], so it doesn't seem to be noting any errors with the tiles array in and of itself.

**Comment by romebell** [comment]
Double check your `index.html` see what class is on the `tiles` 

I responded here { [response](https://github.com/jtreeves/matches-and-patches/commit/a37f82d5bdf706d6846270fff0807e553835ef4c#r43813952) }

**Comment by romebell** [comment]
```javascript
const tiles = document.querySelectorAll('.tiles'); // you have .tile
```

**Comment by romebell** [comment]
I can reopen this issue needed.

**Comment by jtreeves** [comment]
I tried changing it to tiles, but it's still giving me the same issue. I thought I would have to use 'tile' instead of tiles because all the elements that I want to grab have a class of 'tile'; it's just that their parent element has a class of 'tiles'.

**Comment by romebell** [comment]
Update to currently working on `generateCards` function.

```javascript
function generateCards() {
   // Write code here
}
```

**Comment by romebell** [comment]
```javascript
function generate16Tiles(color, shapesArray) {
    const tilesArray = [];
    
    for (let i = 0; i < 4; i++) {
        let eachShape = shapesArray[i];

        for (let j = 0; j < 4; j++) {
            const newTile = document.createElement('div');
            newTile.classList.add('title', color, eachShape);
            tilesArray.push(newTile);
        }
    }
    
    tilesArray.forEach((tile, idx) => {
        if (idx === 0 || idx === 4 || idx === 8 || idx === 12) {
            tile.classList.add('one');
        } else if (idx === 1 || idx === 5 || idx === 9 || idx === 13) {
            tile.classList.add('two');
        } else if (idx === 2 || idx === 6 || idx === 10 || idx === 14) {
            tile.classList.add('three');
        } else if (idx === 3 || idx === 7 || idx === 11 || idx === 15) {
            tile.classList.add('four');
        }
    });

    console.log(tilesArray);
    return tilesArray;
}

const redTiles = generate16Tiles('red', ['triangle', 'square', 'circle', 'hexagon']);
const blueTiles = generate16Tiles('blue', ['triangle', 'square', 'circle', 'hexagon']);
const yellowTiles = generate16Tiles('yellow', ['triangle', 'square', 'circle', 'hexagon']);
const greenTiles = generate16Tiles('green', ['triangle', 'square', 'circle', 'hexagon']);

const allTiles = [...redTiles, ...blueTiles, ...yellowTiles, ...greenTiles];
console.log(allTiles);
```
