### ISSUE TITLE
Jackson Reeves - Uncaught Type Error

### ISSUE THREAD

**Issue by jtreeves** [jtreeves/matches-and-patches#4]
- [x] Cannot read property 'append' of undefined at changeBoard (app.js:293)
- [ ] The app is doing what I want it to do at this point in the code block (let you click on a tile, then click on a patch, then the tile shows up at that patch), but I'm getting this error message. Do I need to worry about this?

**Comment by romebell** [comment]
<img width="489" alt="Screen Shot 2020-11-07 at 7 05 17 PM" src="https://user-images.githubusercontent.com/13144457/98455965-3f58e480-212c-11eb-9e77-ccdca90b5a88.png">

**Comment by romebell** [comment]
The issue that I am noticing is when you made the array `activePatch` array `278`. On line `290` with your `userChoicePath`, you are trying to access the first element in the array, but it's `empty`; therefore, you will get an `undefined`. 

Probably what you may want to do is the following:

```javascript
function changeBoard() {
   let userChoicePatch = selectPatch()[0]
   let userChoiceTile = selectTile()[0]
   userChoicePatch.append(userChoiceTile)
   opponentMove()
}
```

If this doesn't work, let me know. 🙏🏽

**Comment by jtreeves** [comment]
I tried that, but I still got the errors
![Screen Shot 2020-11-07 at 11 43 19 PM](https://user-images.githubusercontent.com/15839768/98457193-26aff500-2153-11eb-80dc-d49ac2bc359d.png)
