### ISSUE TITLE
Jackson Reeves - Adding Event Listeners without the DOM

### ISSUE THREAD

**Issue by jtreeves** [jtreeves/matches-and-patches#5]
- [x] Can I use jQuery?
- [x] Currently, I have a Node array that I got from a querySelector in addition to an object that I made. They should both contain the same things, but I can't make them work with one another efficiently

**Comment by jtreeves** [comment]
I essentially need to add event listeners to non-DOM elements; or turn things into DOM elements, without losing all their other features (e.g., if it's an object, that would include all their key-value pairs)

**Comment by romebell** [comment]
- [ ] I recommend not using jQuery given that we haven't covered it, and it will be a new technology that you would have to learn. Unless you know it already?
- [ ] What lines of code are you referring to? What's the `NodeList`?


Response to { [this](https://github.com/jtreeves/matches-and-patches/issues/5#issuecomment-723534651) }:
- [ ] I'm not sure what you mean by non-DOM elements. Are you referring to elements that you have made by not have added to the DOM?
